services:
  multi-comfyui:
    restart: always
    build:
      dockerfile: Dockerfile
    tty: true
    container_name: comfyui-gateway
    image: bitflowinc/multi-comfyui-gateway:latest
    env_file:
      - comfyui-gateway.env
    volumes:
      - "./workflow:/work/workflow"
      - "./caddy:/work/caddy"
    ports:
      - "80:80"
      - "9000:8080"
    command: ["caddy", "start", "--config", "/work/caddy/Caddyfile"]